//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHAPHANG
    {
        public int ID { get; set; }
        public int IDHH { get; set; }
        public string IDNCC { get; set; }
        public string IDKHO { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<double> DONGIA { get; set; }
    
        public virtual tb_HANGHOA tb_HANGHOA { get; set; }
        public virtual tb_NHACUNGCAP tb_NHACUNGCAP { get; set; }
    }
}
